import { Container, Typography, Button, Box, Stack, AppBar, Toolbar } from '@mui/material';
import { useNavigate } from 'react-router-dom';
import { getToken } from '../utils/request';
import UserMenu from '../components/UserMenu';

export default function Landing() {
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default' }}>
      <AppBar position="static" color="transparent" sx={{ px: { xs: 2, md: 6 } }}>
        <Toolbar
          disableGutters
          sx={{ minHeight: 64, display: 'flex', justifyContent: 'space-between' }}
        >
          <Box sx={{ display: 'flex', alignItems: 'center' }}>
            <Typography variant="h6" sx={{ fontWeight: 700, letterSpacing: 0.4 }}>
              Luma AI
            </Typography>
          </Box>

          <Box>
            <Stack direction="row" spacing={1} alignItems="center">
              {getToken() ? (
                <UserMenu />
              ) : (
                <>
                  <Button color="inherit" onClick={() => navigate('/login')}>
                    Login
                  </Button>
                  <Button variant="contained" onClick={() => navigate('/register')}>
                    Register
                  </Button>
                </>
              )}
            </Stack>
          </Box>
        </Toolbar>
      </AppBar>

      <Container maxWidth="lg">
        <Box
          sx={{
            minHeight: 'calc(100vh - 64px)',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            textAlign: 'center',
            py: 4,
          }}
        >
          <Typography
            variant="h1"
            component="h1"
            gutterBottom
            sx={{
              fontSize: { xs: '2.5rem', md: '4rem' },
              fontWeight: 800,
              background: 'linear-gradient(90deg, #00e5ff 10%, #7c4dff 90%)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              mb: 2,
            }}
          >
            Luma AI
          </Typography>

          <Typography variant="h5" color="text.secondary" paragraph sx={{ maxWidth: 720, mb: 4 }}>
            Create polished tutorial videos generated by AI and instantly produce intelligent video
            clips for highlights, chapters, and sharing. Fast, simple, and tuned for creators and
            educators.
          </Typography>

          <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}>
            <Button
              variant="contained"
              size="large"
              onClick={() => navigate('/login')}
              sx={{ px: 5, py: 1.75 }}
            >
              Start Building
            </Button>
            <Button
              variant="outlined"
              color="inherit"
              size="large"
              onClick={() => navigate('/demo')}
              sx={{ px: 5, py: 1.75 }}
            >
              Try Demo
            </Button>
          </Stack>
        </Box>
      </Container>
    </Box>
  );
}
